### ISSUE TITLE
remove `{SPECIAL_NOTES}`

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/Flight_Freedom#12]
they're deprecated

(personally I wish `wmllint` could remove them for me, but according to wesnoth/wesnoth#6403, apparently a warning from `wmlscope` is all we're going to get)

**Comment by jgerrish** [comment]
If you're still looking for help with this, I wouldn't mind taking a look.  I've been messing with Wesnoth lately and used to do Lua work with WoW, so I've been looking for a small task to contribute to.

Even if you're already in the process of fixing this, I just wanted to say thanks for the mod, code and being welcoming to new developers.  It's a nice act and it's appreciated.

**Comment by cooljeanius** [comment]
So, [23acd73](https://github.com/cooljeanius/Flight_Freedom/commit/23acd73e10410517f8abd3cc3279b3850826cc1a) got most of them, I just have to remove the custom `{SPECIAL_NOTES}` macros that this campaign defines for itself now... which also means removing the `# wmllint: match {ABILITY} with {NOTE}` comments so that `wmllint` stops trying to put them back in.

**Comment by jgerrish** [comment]
I can't help with this, I'm sorry.  Sounds like you're running things fine.

**Comment by cooljeanius** [comment]
> I can't help with this, I'm sorry. Sounds like you're running things fine.

oh ok well thanks for the offer anyways then!

**Comment by cooljeanius** [comment]
So @MadMax3947 is fixing this with [4e73846](https://github.com/MadMax3947/Flight_Freedom/commit/4e73846e8a79aed2b90732640386879e7023ba4b); I'm going to keep this assigned to myself for now, though, since it's up to me to merge it...

**Comment by cooljeanius** [comment]
Should be fixed on the 1.17 branch as of [02231e1](https://github.com/cooljeanius/Flight_Freedom/commit/02231e1dc41da82716eed128c3b6353e54d5af53)

**Comment by cooljeanius** [comment]
leaving this open until I merge the 1.17 branch back to master

**Comment by cooljeanius** [comment]
cross-referencing this against wesnoth/wesnoth#6403, as I have an unanswered question there that's relevant to this issue

**Comment by cooljeanius** [comment]
#31 should close this when merged (assuming we can resolve the merge conflicts properly)
