### ISSUE TITLE
Let Malakar keep his spear (if he picked one up) after breaking free from slavery

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/Flight_Freedom#2]
This would happen in S04a, Caravan

**Comment by cooljeanius** [comment]
putting this off until a post-BfW-1.16 release

**Comment by cooljeanius** [comment]
Looking at how the spear variations are implemented now, this might be rather difficult... but then again, if I have to clean up the existing spear variations *anyways*... I dunno... see these `wmllint` messages:
```
"/Users/ericgallager/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.16/data/add-ons/Flight_Freedom/units/drakes/Slave.cfg", line 206: [variation] is missing required variation_id attribute
"/Users/ericgallager/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.16/data/add-ons/Flight_Freedom/units/drakes/Slave.cfg", line 78: variation_name should be renamed as variation_id and/or marked as translatable
"/Users/ericgallager/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.16/data/add-ons/Flight_Freedom/units/drakes/Worker.cfg", line 210: [variation] is missing required variation_id attribute
"/Users/ericgallager/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.16/data/add-ons/Flight_Freedom/units/drakes/Worker.cfg", line 79: variation_name should be renamed as variation_id and/or marked as translatable
"/Users/ericgallager/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.16/data/add-ons/Flight_Freedom/units/drakes/Worker_Malakar.cfg", line 201: [variation] is missing required variation_id attribute
"/Users/ericgallager/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.16/data/add-ons/Flight_Freedom/units/drakes/Worker_Malakar.cfg", line 87: variation_name should be renamed as variation_id and/or marked as translatable
```

**Comment by knyghtmare** [comment]
Not difficult, you have to change 2 lines in each of the files

**Comment by cooljeanius** [comment]
> Not difficult, you have to change 2 lines in each of the files

Really? I thought it'd mean creating an entirely new variation for each of his stages...

**Comment by cooljeanius** [comment]
> > Not difficult, you have to change 2 lines in each of the files
> 
> Really? I thought it'd mean creating an entirely new variation for each of his stages...

@knyghtmare can you please show your 2-line solution?

**Comment by knyghtmare** [comment]
```ini
variation_id=weapon
variation_name=_"Armed Drake Guerilla"
```
Seems you have fixed it

**Comment by cooljeanius** [comment]
> ```ini
> variation_id=weapon
> variation_name=_"Armed Drake Guerilla"
> ```
> 
> Seems you have fixed it

I don't think this did actually fix it, but I guess I'll have to retest to be sure...

**Comment by cooljeanius** [comment]
ok so yeah I just retested and this isn't actually fixed

**Comment by cooljeanius** [comment]
yeah those lines are only in `Worker.cfg` and `Worker_Malakar.cfg` (and also `Slave.cfg` with a slight difference); to fix this I'd have to put them in `Chieftain.cfg`, `Lord.cfg`, and `Legend.cfg`, too...

**Comment by cooljeanius** [comment]
maybe if I just use the `inherit=yes` key to the `[variation]` tag, this will be easier?

**Comment by cooljeanius** [comment]
ok as of ac8f3d2 I think I've figured it out for the case where he picked up a spear; still need to test the case where he didn't pick one up, though...

**Comment by cooljeanius** [comment]
ok I've tested the other case now, too, so I'm going to close this as fixed now.
