### ISSUE TITLE
Comments on po-file for branch 1.18

### ISSUE THREAD

**Issue by k-konami** [cooljeanius/Flight_Freedom#28]
I wrote some comments on ja.po (for branch-1.18). I extracted and listed them at the bottom.
Roughly, there are three types.
 type_1: a period may be missing at the end of a sentence
 type_2: some that I think may be a writing error.
 type_3: words that were not listed by checking the dictionary because I am not familiar with slang etc.
Note: None of these affect the translation work.

Please check the above.(In practice,  these are not major problems.)

<POT/po item ID> / < comment >
(Search for ‘#po: ’ in _Poedit_ for a quick jump.)
-   51 #po: have no '.'
-  165 #po: "a weeks time" -> "in a week's time" ?
-  366 #po: have no '.'
-  368 #po: "Berserker frenzy" = "berserk" ?
-  378 #po: The id of this [damege] may be a mistake for defend_only.
 (see  source line#531 "id=attack_only")  ( macros/weapon-specials.cfg )
-  681 #po: "by the Eyes" -> "by the eyes" ?
-  695 #po: Melrithan? or Melrithian?  See id:502
-  756 #po: blikker?
-  934 #po: "If need be find" -> "If need be, find" ?
- 1015 #po: emnity -> enmity ?
- 1215 #po: "Murderer" ->  "murderer" ?
- 1252 #po: The following two could mean almost the same thing.
     "place the Saurians under your command"
     "add to your army"
- 1682 #po: "Abyssal" -> "abyssal" ?
- 1733 #po: Giant ants -> Cave ants
- 1749 #po: The Major Thunder Spirits -> The Major Spirits
- 1751 #po: The Thunder Spirits -> The Minor Spirits

 ---

**Comment by MadMax3947** [comment]
Fixed most of this in https://github.com/cooljeanius/Flight_Freedom/pull/25/commits/93a4ccfd3114198c75bbf99c9d6a771a5e557403

**Comment by cooljeanius** [comment]
> Fixed most of this in [93a4ccf](https://github.com/cooljeanius/Flight_Freedom/commit/93a4ccfd3114198c75bbf99c9d6a771a5e557403)

so, ok to close this, then?

**Comment by cooljeanius** [comment]
OK, I think this is done now.

**Comment by cooljeanius** [comment]
Note that now that #31 is merged, future PRs of this nature should go against the `master` branch.
