### ISSUE TITLE
explicitly specify carryover percentages

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/Flight_Freedom#7]
This could be a step towards varying carryovers by difficulty. The default when left unspecified is 80%, so I'm thinking of having `carryover_percentage` generally be either `{ON_DIFFICULTY 80 70 60}` or `{ON_DIFFICULTY 80 60 40}`. Also consider varying the early finish bonus by difficulty, too?

**Comment by cooljeanius** [comment]
> Also consider varying the early finish bonus by difficulty, too?

...oh, and `carryover_add`, too.

**Comment by knyghtmare** [comment]
`{ON_DIFFICULTY 80 60 40}` seems too extreme

`{ON_DIFFICULTY 80 70 60}` seems okay

**Comment by cooljeanius** [comment]
> `{ON_DIFFICULTY 80 60 40}` seems too extreme
> 
> `{ON_DIFFICULTY 80 70 60}` seems okay

ok I'm going with the latter

**Comment by cooljeanius** [comment]
almost done as of [00e0e02](https://github.com/cooljeanius/Flight_Freedom/commit/00e0e02a5ef44af9f1d1ffb2bc8379ac6ece624a)

**Comment by cooljeanius** [comment]
ok as of [f3c9ce4](https://github.com/cooljeanius/Flight_Freedom/commit/f3c9ce440643041c2d5f229aa72ca353d55ba49c) this is probably in "good enough for now" status now; closing
